# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
org.gradle.configuration-cache=false
kotlin.code.style=official

# Use JDK 17
org.gradle.java.home=C\:\\Program Files\\Eclipse Adoptium\\jdk-17.0.20.101-hotspot

# Disable the buggy worker API for Kapt/KSP version parsing
kapt.use.worker.api=false
